# Generated by Django 5.0.1 on 2024-02-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование:')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Слаг')),
            ],
        ),
    ]
